### ISSUE TITLE
Add B->D* form factor constraints from the lattice

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#101]
There are two lattice determinations of the B->D^* form factor(s) at zero recoil / maximum q^2:
- [HPQCD from 2017](http://inspirehep.net/record/1639448)
- [Fermilab/MILC from 2014](http://inspirehep.net/record/1283613)

Their form factor definitions to be translated to ours through e.g. the table I in [this paper](https://arxiv.org/pdf/1707.09509.pdf) and the appendix of [this paper](https://arxiv.org/pdf/hep-ph/9712417.pdf), see also the formulas in [the HPQCD paper](http://inspirehep.net/record/1639448), eq. (5).

Add both constraints as two independent univariate gaussian constraints to ```eos/constraints/B-to-V-form-factors.yaml```, similarly to what has been done in ```eos/constraints/B-to-P-form-factors.yaml``` for e.g. B->D transitions.

**Comment by akokulu7** [comment]
@dvandyk resolved by  6e779d7.

**Comment by dvandyk** [comment]
Please don't close an issue until the pull request is merged.

**Comment by akokulu7** [comment]
@dvandyk please see the new commit 96665ac.
