### ISSUE TITLE
Tensor operators in b->clnu decays

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#105]
Add effects of tensor operator to the decays
 - [x] B->D l nu
 - [x] B->D^* l nu
 - [ ] Lambda_b -> Lambda_c l nu

still need to find references for the formulas.

@akokulu7 this is just for book keeping for the time being.

**Comment by dvandyk** [comment]
Literature:

  - [Faller et al.](https://arxiv.org/abs/1105.3679)
  - [Bernlochner et al.](https://arxiv.org/pdf/1703.05330.pdf)
  - [Jung, Straub](https://arxiv.org/pdf/1801.01112.pdf)
  - [Datta et al.](https://arxiv.org/pdf/1702.02243.pdf)

**Comment by akokulu7** [comment]
Generic NP contribution to B->D^*lnu including tensor operators effects is added. Resolved by Pull Request #122  .

**Comment by dvandyk** [comment]
Closing this, since we're tracking Lambda_b -> Lambda_c l nu, including 4-differential width now in #137.
