### ISSUE TITLE
eos-plot client

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#11]
- add python module to load the various eos HDF5 data file formats
 - possible output modes
   - scatter plot (new)
   - heat map
   - contours (w/ KDE)

**Comment by dvandyk** [comment]
Basic support has been added with 01a61d6b2d4d3ad7775ae429a912c63ecd17818f. Histogram only for the time being.

@fredRos I would love to use scipy's 'stats.gaussian_kde', see
    http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html
in order to get rid of figtree. Do you see any reason not to use it?

**Comment by fredRos** [comment]
Yes, I started out with gaussian_kde. It's terribly slow if you have hundreds of thousands of points. Figtree is way faster. I provide a python wrapper and the original author does so, too

https://github.com/vmorariu/figtree#python-wrapper

**Comment by dvandyk** [comment]
I have added scripts for the 1D and the 2D case which can
  - produce histograms
  - optionally produce 1D KDE plots using gaussian_kde

I will replace the gaussian_kde usage with figtree in the future. Both
scripts are documented in the manual.
