### ISSUE TITLE
Ubuntu installation troubles

### ISSUE THREAD

**Issue by DavidMStraub** [eos/eos#126]
Ubuntu 18.04.1 LTS

- Installed all dependencies listed in the [manual](https://eos.github.io/manual/manual.pdf) section 1.1.2
- Installed `Minuit` and `libpmc` from package cloud (worked)
- Tried to install `eos` from package cloud. Failed.

```
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 eos : Hängt ab von: libhdf5-10 (>= 1.8.16) ist aber nicht installierbar
       Hängt ab von: libboost-filesystem1.58.0 ist aber nicht installierbar
       Hängt ab von: libboost-python1.58.0 ist aber nicht installierbar
       Hängt ab von: libboost-system1.58.0 ist aber nicht installierbar
       Hängt ab von: libgsl2 ist aber nicht installierbar
```

Am I missing something?

**Comment by dvandyk** [comment]
David, for your purpose you will need to install from source. The commit you seek is not part of any release yet. Sorry.

Regarding your problem, I need to investigate.

**Comment by dvandyk** [comment]
@DavidMStraub Ok, for some reason unknown to me the automatic deployment is not working. To add insult to injury, apparently your binary dpkg uses dependencies for xenial, rather than bionic in the build.
This will take a bit.

**Comment by DavidMStraub** [comment]
Joint task force ```bionic``` finds that the following changes help:
```
diff --git a/debian/control-bionic.in b/debian/control-bionic.in
index 191d1d5..d5fab31 100644
--- a/debian/control-bionic.in
+++ b/debian/control-bionic.in
@@ -1,6 +1,6 @@
 Package: eos
 Version: @VERSION@
 Architecture: amd64
-Depends: libc6 (>= 2.19), libstdc++6 (>= 4.8), minuit2 (>= 5.28.00), libpmc (>= 1.01), libhdf5-10 (>= 1.8.16), libboost-filesystem1.58.0, libboost-python1.58.0, libboost-system1.58.0, libgsl-dev
+Depends: libc6 (>= 2.19), libstdc++6 (>= 4.8), minuit2 (>= 5.28.00), libpmc (>= 1.01), libhdf5-100 (>= 1.8.16), libboost-filesystem-dev, libboost-python-dev, libboost-system-dev, libgsl-dev
 Maintainer: Danny van Dyk <danny.van.dyk@gmail.com>
 Description: EOS -- A HEP program for flavor observables
```
