### ISSUE TITLE
SignalPDF for B->D* l nu

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#128]
[From meeting with Itoh-san, Hara-san and Hideky-san (@hmiyake).]

@cBobeth taking lead on this.
- [ ] add full angular PDFs for B->D l nu, 
- [ ] add full angular PDFs for B->D* l nu.

**Comment by dvandyk** [comment]
@cBobeth, @akokulu7 any progress? :-)

**Comment by akokulu7** [comment]
@dvandyk and @cBobeth please find my implementation for  the full angular distribution for B->D^* l nu in PR #142. cheers.

**Comment by dvandyk** [comment]
Since PR #142 has been merged, we can close this.
