### ISSUE TITLE
P -> P form factors: BCL2008

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#13]
When reviewing the BCL2008 parametrization in EOS for an ongoing project,
I realised that the f_0 form factor has been incorrectly parametrized:

 - the pole used is the J^P = 1^- resonance mass
 - the equation of motion to impose Im(f_0) = (q^2 - t_+)^3/2
   is incorrectly used

```C++
            virtual double f_0(const double & s) const
            {
                const double z = _z(s), z2 = z * z, z3 = z * z2;
                const double z0 = _z(0), z02 = z0 * z0, z03 = z0 * z02;
                const double zbar = z - z0, z2bar = z2 - z02, z3bar = z3 - z03;

                // note that f_0(0) = f_+(0)!
                return _f_plus_0 / (1.0 - s / Process_::m2_Br1m) * (1.0 + _b_zero_1 * (zbar - z3bar / 3.0) + _b_zero_2 * (z2bar + 2.0 * z3bar / 3.0));
            }
```

@fredRos Sorry about that. I introduced that error.

**Comment by fredRos** [comment]
Can you show or estimate what the difference to the correct parametrization is? Will it impact ongoing analyses?

**Comment by dvandyk** [comment]
The difference to the correct parametrization does not matter as long as you carry out a fit yourself (i.e., not rely on BCL2008 to match a published parametrization). I cannot see that any ongoing or past analyses are affected.

**Comment by fredRos** [comment]
> I cannot see that any ongoing or past analyses are affected.

Excellent! So why did you apologize :smile: ?
