### ISSUE TITLE
Various improvements to the parameter descriptions

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#171]
Depends on closing #165:

 - [x] Add LaTeX representation for all form factor parameters
 - [x] Add LaTeX representation for masses
 - [x] Add LaTeX representation for CKM parameters

 - [x] Retire parameter ```lambda_B_p```, and replace with 1 / ```B::1/lambda_B_p``` (mind the test cases!)
 - [x] Rename all ```B->K::a_{1,2,4}@{1,2.2}GeV``` to ```K::...``` (mind the test cases!)
 - [x] Retire parameters ```B->K^*::a_{perp,par}``` and replace with existing ```K^*::..``` (mind the test cases!)

 - [x] Replace ```mu``` in eos/rare-b-decays/ with a new parameter ```b->s::mu_b``` (to be placed in sm-and-eft.yaml, b->s  EFT group)
 - [x] Rename ```G_Fermi``` to ```mu->enunubar::G_Fermi```
 - [x] Rename ```hbar``` to ```QM::hbar```

**Comment by dvandyk** [comment]
Any updates on this issue?

**Comment by gubernari** [comment]
No sorry, I was busy with the other issues and I forgot about this. I will look into it after we close issue191

**Comment by dvandyk** [comment]
Moving to 0.4

**Comment by SKuerten** [comment]
- what was the consensus for ```G_Fermi```? Something like ```QM::G_Fermi``` or ```decay-constant::G_Fermi``` (from Standard Model & EFT Parameters)?
- The 4th case which was discussed in the meeting was ```mu``` to ```b->s::mu_b```, correct?

**Comment by dvandyk** [comment]
@SKuerten it was ``WET::G_Fermi``. And for the scale, ``b->s::mu_b`` is correct.

**Comment by SKuerten** [comment]
How do we want 
 - [ ] Retire parameter ```lambda_B_p```, and replace with 1 / ```B::1/lambda_B_p``` (mind the test cases!)
exactly?

There is already a parameter called ```B::1/lambda_B_p``` with a different value for ```lambda_B_p```  "cf. [BHvD2010] central value: 0.485 GeV" vs. "cf. [GKvD2018] central value: 0.460 GeV".
When I just change ```lambda_B_p``` to 1 / ```B::1/lambda_B_p``` all the test-cases will fail. How should I solve this? I could introduce ```B::1/lambda_B_p@BHvD2010``` ... I am not sure if this is wanted.

**Comment by gubernari** [comment]
I'm not sure one should do such a replacement, it would imply to change many parts of the code
If I manage we can discuss this tomorrow morning

**Comment by SKuerten** [comment]
@gubernari I discussed with Danny in a different chat and did the lambda_B_p accordingly - that is solved.

The 1st point on the list is rather involved in 1811.00983 :
In the yaml file there are occurences of something like 'B->pi::alpha^f+_0@BSZ2015'
@gubernari what does the alpha mean in that expression? In the paper only f+/f-/f0 etc. are noted. Do you know what's the most sensible LaTeX representation?
- $f_+^{B \to \pi}$
- $f_+^{B \to P}$ or V depending on pseudoscalar or Vector
- or $\alpha^{f_+^{B \to \pi}}$
?

**Comment by gubernari** [comment]
alpha are the coefficients of the z expansion. See eq. 3.4 of 1811.00983
