### ISSUE TITLE
Preparations for EOS on PyPI

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#179]
In order to submit EOS to PyPI we should be able to build the _eos.so extension against static EOS libraries and with minimal linkage against shared objects.

After configuring with ```--enable-static``` and ```CXXFLAGS=-fPIC -DPIC```, I can successfully build ```_eos.so``` linked against all EOS ```.a``` files rather than the ```libeos.la```. However,
we still link against several shared objects for the following reasons:

no static library available on Ubuntu:
 - [ ] libMinuit2

static libraries are built without ```-fPIC```
 - [ ] libgsl.so and libgslcblas.so
 - [ ] libboost_python3-py36.so
 - [ ] libboost_system.so
 - [ ] libboost_filesystem.so

@daritter My plan would be to build a docker image on the basis of ```manylinux1```, build GSL and Boost using PIC. Then build EOS on that system. Any comments?

**Comment by daritter** [comment]
I think it would be fine to ship the shared libraries in the pypi package as long as _eso.so has a correct RPATH/RUNPATH relative to the binary itself? That's how e.g. tensorflow links in lkml in its wheel.

```
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../_solib_k8/_U@mkl_Ulinux_S_S_Cmkl_Ulibs_Ulinux___Uexternal_Smkl_Ulinux_Slib:$ORIGIN/]
```

or numpy

```
$ readelf -d multiarray.cpython-36m-x86_64-linux-gnu.so 

Dynamic section at offset 0x1f5000 contains 29 entries:
  Tag        Type                         Name/Value
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../.libs]
 0x0000000000000001 (NEEDED)             Shared library: [libopenblasp-r0-39a31c03.2.18.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```

So one simple solution is to compile on a manylinux1 normally if you can link all the libraries with relative origin and ship them in your binary.

The bigger problem would be libMinuit2 which depends on all of root ... can you make a eos without that? Or do you have a standalone version of libMinuit2 without root dependencies?
