### ISSUE TITLE
Allow for different spectator quarks in B(*)->D(*) form factors

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#191]
Presently the parameters used in the class ```HQETFormFactorBase``` are for only a light spectator quark. We should

 - [x] add an spectator quark option to the class
 - [x] distinguish between IW parameters for the "d" and the "s" spectator quark
 - [x] make LambdaBar a parameter
 - [ ] make LambdaBar dependent on the spectator quark option

The relevant file is ```eos/form-factors/mesonic-hqet.hh```.

**Comment by dvandyk** [comment]
@gubernari Nico, can we close this? Which changes from branch ```issue191``` have not yet been merged into ```master```?

**Comment by gubernari** [comment]
we can close this.
I think only the very recent (maybe even uncommitted) changes in  ```issue191```  are not in  ```master```

**Comment by dvandyk** [comment]
Closing; changes are already merged into master.
