### ISSUE TITLE
eos-plot{,-1d,-2d}: Add and speed up KDEs

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#20]

**Comment by fredRos** [comment]
There are two options, see https://github.com/fredRos/pyfigtree#historical-note

**Comment by fredRos** [comment]
I think we will have less work if we just rely on existing packages. A simple but pretty solution is https://github.com/SebastianBocquet/pygtc, a more feature-complete solution is https://github.com/cmbant/getdist

**Comment by dvandyk** [comment]
I think it's OK to use any `pip`-installable package.

**Comment by dvandyk** [comment]
Using any other method for smoothing the histograms is also OK. @fredRos you mentioned 'shifted histograms'?

**Comment by dvandyk** [comment]
This had been fixed for some time, using SciPy's gaussian_kde.
