### ISSUE TITLE
Interface to a PyHF (Log)Likelihood

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#24]
Read data from text file, with tabulator-separated columns.

**Comment by dvandyk** [comment]
Pushed a preliminary implementation to branch 'unbinned-llh', see commit ae206d88cf9f64c50e5d5159998d8ffce52104c5 . Note that it does not support per-event weights.

@fredRos Would you mind having a look? I have two questions on how to implement this completely:
  1. As how many observations should we count an unbinned likelihood? As many as the number of events '''N'''? If yes, why? In the limit '''N -> infinity''', the profile likelihood approaches a Gaussian, which we would count as only one observation, don't we? And then further: What about 2D unbinned likelihoods? Those should have twice as many observations as 1D likelihoods, shouldn't they?
  2. How do we determine the significance of the current parameter point with respect to the observations?

**Comment by mchrzasz** [comment]
So I am not sure what you mean by number of observations to be honest. 

But I think I can answer the second question: you do a profile likelihood and you get the error

**Comment by mchrzasz** [comment]
Sorry wrong clic :)

So I am not sure what you mean by observations in the maximum likelihood fit. Where do you want to use them?

The significance you get from delta LL ratio or you are talking about something more advanced?

**Comment by fredRos** [comment]
I left my comments in the commit bef0325, which partially answers your questions. To be more explicit

> As how many observations should we count an unbinned likelihood? As many as the number of events '''N'''? If yes, why? 

For a Gaussian, we use chi2 as the test statistic. Its distribution depends on the number of events (and fit parameters). This is the text book case. 

> In the limit '''N -> infinity''', the profile likelihood approaches a Gaussian, which we would count as only one observation, don't we? 

Yes, but this is an approximation I was never happy about. The above case is clear, our use of approximate likelihoods as observations is an approximation because we didn't know how to do it better. But don't let the approximation dictate what the result should be when we know the answer.

> And then further: What about 2D unbinned likelihoods? Those should have twice as many observations as 1D likelihoods, shouldn't they?
> How do we determine the significance of the current parameter point with respect to the observations?

These questions are connected: you need a test statistic, that usually depends on the parameter point. To remove this bias towards larger p values, we applied the correction that is correct for a multivariate Gaussian with a linear model at the global mode. For arbitrary pdfs, we don't know what test statistic to choose. One general choice would be to generate events from the pdf and compute the likelihood each time, then use the likelihood as the test statistic. But this is case is much more involved, you would have to run a Markov chain or similar in the general case to create new events. So the answer is, I don't know how to determine the significance in general in a simple-enough way to put it into the current scheme.

**Comment by dvandyk** [comment]
@fredRos, @mchrzasz: Thanks for you input. I think I will move '''significance()''' out of '''LogLikelihoodBlock'''. Instead, I'll use the Visitor pattern, and create a '''SignificanceCalculator'''. I haven't decided yet what to do with '''samples(gsl_rng *)'''.

**Comment by dvandyk** [comment]
Update after discussions with Andrea Mauri and Rafael Silva Coutinho: For the general multivariate case, a test statistic can be computed using Monte Carlo methods. For an overview, see [https://arxiv.org/pdf/1006.3019.pdf](the paper by Mike Williams). I think it's a good idea to start with the Mixed-Sample Method from this paper, see eq. (3.4). My reasoning is that this method has (in a certain limit) an analytically computable test statistic, see eqs. (3.5) and (3.6).

The Mixed-Sample Method requires a small number of samples from the SignalPDF in the calculation of the test statistic T. Since none of the present EOS MC samplers is suitable to run 'unattended', i.e., without the steering by a human, we need a new sampler. For this reason Andrea is going to implement an Acceptance-Rejection based sampler.

TODOs
- [ ] delete `significance()` out of `LogLikelihoodBlock`
- [ ] add a `TestStatistics` base class, with `ChiSquare` and `Empty` as initial descendants
- [ ] write a `GoodnessOfFitCalculator` that visits the primary test statistic of each `LogLikelihoodBlock`
- [ ] write a new `eos-goodness-of-fit` client that display the results of the `GoodnessOfFitCalculator`
- [ ] implement `AcceptanceRejectionSampler`
- [ ] implement nearest-neighbour algorithm
- [ ] implement `MixedSample` as a test statistic, and add to `GoodnessOfFitCalculator`

**Comment by fredRos** [comment]
Wouldn't it be more efficient in programmer time to add a dependency to a sampler? I think EOS already has too many sampling algorithms implemented that should really be in a separate package as they have nothing to do directly with physics. And yes, I'm the main person to blame for this state of affairs.

**Comment by dvandyk** [comment]
I do prefer having the sampling algorithms as part of the EOS package. Having installed EOS in more than twenty different computing environments by now, this level of self-containedness has been **very helpful**. Also, Andrea seemed to be quite happy to get his hands dirty!

**Comment by mchrzasz** [comment]
I agree with Danny. It's rather simple to implement and having one less dependece makes a huge different if more people are going to use EOS.

**Comment by fredRos** [comment]
Ok, I agree. We have had similar experience with BAT. Dependencies in C++ are a pain. Less so but still somewhat of a pain in python. This is what I like about the julia language where users don't have to install packages themselves but dependencies are installed automatically. Much better for the developer and the user.

**Comment by dvandyk** [comment]
Closing this issues:
 - EOS samplers have been removed in favour of pypmc
 - WET likelihoods will beha dled by smells
 - PMC final mixture densities can be handled by EOS likelihood.

**Comment by mreboud** [comment]
I think this implementation is still worthwhile. LHCb has e.g. an ongoing analysis where Wilson coefficients are extracted using an unbinned likelihood fit. Concerning the statistics, MC is probably the only reliable approach. I would threfore leave an empty statistic in the C++ implementation (and maybe a couple of Warnings...).
