### ISSUE TITLE
[C++14] Replace all uses of typedef with using

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#243]
From a discussion with @SKuerten: Instead of code that looks like
```C++
typedef QualifiedName KeyType;
```
we should use the more readable and modern code
```C++
using KeyType = QualifiedName;
```
@mreboud Want to try your hand on this one?

**Comment by mreboud** [comment]
Yes!

**Comment by mreboud** [comment]
@dvandyk Should I make this replacement everywhere? What about external codes such as e.g. integrate-curbature... ?

**Comment by dvandyk** [comment]
@mreboud I would avoid external code, of which integrate-cubature is presently the only one AFAICS.
