### ISSUE TITLE
Access a sub-sample of a constraints set at run-time

### ISSUE THREAD

**Issue by mreboud** [eos/eos#257]
It would be useful to have the possibility to specify a subset of a kinematic range of a constraint at run-time.
This could be done by adapting the structures, based on ConstraintEntryBase in [/eos/constraint.cc](https://github.com/eos/eos/blob/master/eos/constraint.cc), that have a kinematics option.

**Comment by dvandyk** [comment]
As a first attempt, I would specify a range of elements to use, e.g. by appending a ```begin``` and ```end``` option to the constraint's name. Example:

```
B^0->D^+e^-nu::BRs@Belle-2015A;begin=0,end=10   # this would be equivalent to all elements           
B^0->D^+e^-nu::BRs@Belle-2015A;begin=0,end=6   # this would be equivalent to the first 6 elements
```

The relevant code is here: https://github.com/eos/eos/blob/58563acc2efdda3eef1261e17f192eac252fc2de/eos/constraint.cc#L1135-L1170

I didn't see a built-in way to copy only a subvector or a submatrix in the GSL. While views exist, I don't see a memcpy or anything like that.

**Comment by mreboud** [comment]
Indeed I don't see how we can memcpy a subvector/submatrix. Unless you have a better solution, I will get a view and use it to initialize the new structure.

**Comment by dvandyk** [comment]
I think we can safely skip the view aspect, since we know who created the vectors and matrices (i.e., us) and they are stored consecutively in memory.

**Comment by mreboud** [comment]
What is the aim of the "response" option in the MultivariateGaussianCovarianceConstraintEntry structure? I see that it is a `n_measurements * n_predictions` matrix and wonder how it should be treated when specifying a sub-sample of the measurements?

**Comment by dvandyk** [comment]
Some experimental analyses do not provide unfolded results, but require instead forward folding of the theory predictions to the detector level. I would suggest for the time being to only apply the range reduction to the index of corresponding to the ```n_measurements``` dimension.

**Comment by dvandyk** [comment]
@ESEberhard @mreboud Can we get a clean PR that fixes the outstanding problems? I think Mr Eberhard has two commits ready for that.

**Comment by mreboud** [comment]
I do this asap (today)

**Comment by dvandyk** [comment]
I think this can be closed now.

@mreboud Please reopen if I'm wrong...

**Comment by mreboud** [comment]
Well, the fix is not documented and only concerns MultivariateGaussain, so we may want to extend this fix in the future. Furthermore this is really not user-friendly because one needs to find the number of measurements that are below a given energy threshold. Being able to specify the maximal energy to be included in the fit would be much more simple to use.

**Comment by ESEberhard** [comment]
I strongly agree!
