### ISSUE TITLE
python configuration

### ISSUE THREAD

**Issue by fredRos** [eos/eos#26]
Apart from describing it in the manual, which means copying that part over from the b2tip report, there is another point to work on.
it seems that now it just supports python2.7, or it picks this automatically on my machine because python

```
ll /usr/bin/python
lrwxrwxrwx 1 root root 9 Dec 21  2013 /usr/bin/python -> python2.7
```

Perhaps we can also direct configure to the python version we want?

**Comment by dvandyk** [comment]
The manual is being worked on right now. I still got a couple of pages of hand-written notes, that need
transferring to LaTeX.

With regards to the Python version: We currently test for a minimal Python version in `configure.ac` with
`AM_PATH_PYTHON`:
```m4
if test "x$enable_python" == xyes ; then
        AM_PATH_PYTHON(2.7.0)
        PY_PREFIX=`$PYTHON -c 'import sys ; print sys.prefix'`
        PYTHON_LIBS="-lpython$PYTHON_VERSION"
        PYTHON_CFLAGS="-I$PY_PREFIX/include/python$PYTHON_VERSION"
        AC_SUBST([PYTHON_LIBS])
        AC_SUBST([PYTHON_CFLAGS])
fi
```
In principle, this should allow to install the EOS-Python interface for any Python version, by simply
changing the PYTHON environment variable (i.e.: `PYTHON=python3 ./configure ...`), which I successfully tested just now. However, building against Python3 presently fails on my system:
1. The python code to determine PY_PREFIX in the above snippet from the `configure.ac` is not python3 compatible. I changed that locally by adding parentheses to the call to `print`.
2. On Debian/Ubuntu, we need to select the correct build-version of `libboost_python.so`, which
is selected via the suffix '-py27' or '-py34'. Presently, `libboost_python.so` points to `libboost_python-py27.so`, so for a Python3 build we need to relay the suffix to the Makefile. I have changed this locally as well.

This seems to work:
```
dvandyk@delta usability (usability) $ python3
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eos
>>> p = eos.Parameters.Defaults()
>>> k = eos.Kinematics(**{ "s_min": 1.0, "s_max": 6.0 })
>>> o = eos.Options(**{ "form-factors": "KMPW2010", "q": "d", "l": "mu"})
>>> obs = eos.Observable.make("B->K^*ll::BR@LargeRecoil", p, k, o)
>>> obs.evaluate()
2.0260230655294568e-07
```

I will close this issue once all commits are in master and the process of building against Python3 is documented in the manual.
