### ISSUE TITLE
Add an option in analysis.optimize to start at a random point of the parameters space

### ISSUE THREAD

**Issue by mreboud** [eos/eos#264]

**Comment by dvandyk** [comment]
I think it's easier than that:

 - ``eos/statistics/log-posterior.hh`` and ``eos/statistics/log-posterior.cc`:
   - add forward iterator: ``using PriorIterator = ForwardIterator<PriorIteratorTag, const LogPriorPtr>;``
   - add ``PriorIterator begin_priors() const`` and ``PriorIterator end_priors() const``, which simply ``return _priors.begin();`` and ``return _priors.end();``
 - ``python/_eos.cc``, line 468
```C++
        .def("log_priors", range(&LogPosterior::begin_priors, &Log:posterior::end_priors))
```

Then it's as easy as running
```Python
    point = [p.inverse_cdf(rng.uniform()) for p posterior.priors()]
```

**Comment by dvandyk** [comment]
@mreboud What's the progress on this one?

**Comment by mreboud** [comment]
It is on my non urgent todo list, I will try to take care of it in the week
