### ISSUE TITLE
Wrong casting of the yaml covariance matrix

### ISSUE THREAD

**Issue by mreboud** [eos/eos#265]
For some reasons, plotter.py sometimes manage to read a YAML covariance matrix as a `np.str` array instead of an array of floats, causing the somewhat obscure error:

`ufunc 'sqrt' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

As a temporary fix, I suggest to enforce casting to float by adding a `np.float`.

**Comment by dvandyk** [comment]
Merged.
