### ISSUE TITLE
SignalPDF discussion

### ISSUE THREAD

**Issue by mchrzasz** [eos/eos#27]
So after talking to Danny here are the cliff to be discussed:

What is called now SignalPDF class should be renamed to General PDF. If this is going to be used by e it will create enormous amount of confusion.

Other thing to discuss is the positive definition of a PDF. Talking to Danny I understood that each pdf needs to be positively defined. It is important to be able to change this. For example if we have:

pdf=pdf1+pdf2

We could require that the pdf is positively defined. It might happen that the pdf1 is negative but the whole pdf is positive defined. In rare decays this helps a lot as makes the fit more stable. We have run toys in LHCb and we proved that this approach is unbias. Could we have a switch in each to turn off checking the post def of pdf?

**Comment by fredRos** [comment]
> What is called now SignalPDF class should be renamed to General PDF. If this is going to be used by e it will create enormous amount of confusion.

OK with me, I did not invent the name `SignalPDF`.  We have 'Density` in eos, which is a more general concept but it operates on the log scale so it, too, assumes that the density is > 0.

> In rare decays this helps a lot as makes the fit more stable. We have run toys in LHCb and we proved that this approach is unbias. Could we have a switch in each to turn off checking the post def of pdf?

What exactly did you try to compute, and what (estimator?) is unbiased? Please let me have a look at some material, we can do that by email. 
I and @dvandyk would need to understand what pieces (densities) you need to construct other objects.



> Could we have a switch in each to turn off checking the post def of pdf?

I think this would not work because we work on the log scale, for a negative number the log takes you into complex analysis

**Comment by mchrzasz** [comment]
> What exactly did you try to compute, and what (estimator?) is unbiased? Please let me have a look at some material, we can do that by email. 
I and @dvandyk would need to understand what pieces (densities) you need to construct other objects.

So we tested an unbinned max likelihood estimator in each of the q2 bins. The pdf was K*mumu anglel(with Fl, S3,...) combined with mass pdf (double cristal ball) with background pdf (exponent in mass and chebechew with angles). 

So of course the pdf as described above needs to be positive because the log would be complex. But individual pdfs (for example K*mumu pdf) doesn't need to be positive as other pdf which will be added can be greater and will compensate the negative values. We steted with toys that this procedure is more stable if one has small number of events

We can discuss this in more details on skype/mail

**Comment by fredRos** [comment]
No more action required here
