### ISSUE TITLE
Add parsing of arithmetic expressions to construct new observables at run time

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#270]
Based on the preliminary code by @mreboud and Damla Cavusoglu.

 1. split into multiple files:
     * ```eos/utils/expression.hh```: class declarations for all expression classes in ```namespace eos::exp```
     * ```eos/utils/expression.cc```: class definitions as above, same namespace
     * ```eos/utils/expression-parser.hh```: class declaration for the parser
     * ```eos/utils/expression-parser-impl.hh```: class definitions for the parser
     * ```eos/utils/expression-parser_TEST.cc```: unit tests for the expressions parser
 2. create a new class ```ExpressionObservableEntry``` inheriting from ```ObservableEntry```:
     * ```eos/utils/expression-observable.{cc,hh}```: class declaration and class definition
     * constructor should take only
         - an ```std:string``` object for the expression and possible alias instructions
     * leave the make routine empty for the time being, returning a null pointer
     * make it printable, printing the full expression including the observable names
     * test it by contructing and printing, check the output of the print against a reference value
 3. create a new class ```ExpressionObservable``` inheriting from ```Observable```:
     * ```eos/utils/expression-observable.{cc,hh}```: class declaation and class definiton
     * constructor should take ```Parameters```, ```Kinematics``` and ```Options``` and ```std::shared_ptr<eos::AbstractExpression>```; all should be stored.
     * let ```ExpressionObservableEntry::make``` return a new ```ExpressionObservable``` by simply copying the underlying ```std::shared_ptr<eos::AbstractExpression>```.
     * write a simple test case with an expression that only contains binary operations and constants, and check that it can create a working ```Observable *``` using ```Observable::make()```.
  4.  To be continued...

**Comment by mreboud** [comment]
Step 1 is completed on my branch [eos-parser](https://github.com/mreboud/eos/tree/eos-parser).

**Comment by mreboud** [comment]
Step 2 is completed as well, I used a `unordered_map` for the aliases.
