### ISSUE TITLE
Cacheable observable with no kinematic variables

### ISSUE THREAD

**Issue by mreboud** [eos/eos#281]
With the current implementation of cacheable entries, one cannot enter a cacheable observable with no kinematic variables, e.g.
```
 make_cacheable_observable("ee->ccbar::psi2S_total_width", R"($\Gamma_{\psi(2S)}$)",
            &EEToCCBar::prepare,
            &EEToCCBar::psi2S_total_width),
```

**Comment by mreboud** [comment]
I added a method without kinematics_names and Tuple as we have for regular observables here [https://github.com/eos/eos/blob/f17f92d769d86061b3e5cf74bc0f007be6e3b57e/eos/observable-impl.hh#L114](https://github.com/eos/eos/blob/f17f92d769d86061b3e5cf74bc0f007be6e3b57e/eos/observable-impl.hh#L114), but this causes an error:
```
observables.cc:46:54:   required from here
../../eos/utils/concrete-cacheable-observable.hh:324:40: error: static assertion failed: Need as many function arguments as kinematics names!
         static_assert(sizeof...(Args_) == impl::TupleSize<Tuple_>::size, "Need as many function arguments as kinematics names!");
```

**Comment by dvandyk** [comment]
@mreboud Indeed, there is no support for this, and I'm not sure that it's needed. You're prepare function needs one kinematic variable. What would be the correct one?

I think the decay widths should be regular observables rather than cacheable.

**Comment by mreboud** [comment]
Indeed, so this is not an urgent issue.
