### ISSUE TITLE
Add prior distributions for renormalization scales

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#287]
It would be useful to have a prior to vary a renormalization scale, where <img src="https://render.githubusercontent.com/render/math?math=\ln \mu/\mu_0"> is distributed uniformly in <img src="https://render.githubusercontent.com/render/math?math=[-\ln \lambda, +\ln \lambda]">.

The PDF would be <img src="https://render.githubusercontent.com/render/math?math=\frac{1}{2 \mu \ln\lambda}"> with integration boundaries <img src="https://render.githubusercontent.com/render/math?math=[\mu_0/\lambda, \mu_0 \lambda]">.

The CDF would be <img src="https://render.githubusercontent.com/render/math?math=\frac{1}{2\ln\lambda}\left[\ln \mu - \ln \mu_0/\lambda\right]">.

The inverse CDF would be <img src="https://render.githubusercontent.com/render/math?math=\mu_0 \lambda^{2p - 1}">.

**Comment by mreboud** [comment]
Solved with #290
