### ISSUE TITLE
Move to C++20

### ISSUE THREAD

**Issue by mreboud** [eos/eos#307]
Although C++20 is not urgently needed for the moment, it comes with interesting features that we may use in the future. This requires moving to g++10 (which is possible on Ubuntu 18.04 as well).

**Comment by dvandyk** [comment]
- [ ] ensure/check that the macOS build environment hat c++20 support (clang++ >= 12)
 - [ ] ensure/check that the manylinux2014 image has c++20 support (g++ >= 10)
 - [ ] check that the libstdc++ ABI stable when building on manylinux2014 and running with libstd++ < 10

**Comment by mreboud** [comment]
A first step, C++14 -> C++17, is implemented in this PR #382

**Comment by dvandyk** [comment]
Postponed until ``std::format`` is available in g++ and clang.
