### ISSUE TITLE
Allow users to override entire parameter set by specifying EOS_USER_PARAMETERS env var

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#31]
- [x]  change logic in Impl<Parameters>::load_defaults() to load the full set of parameters;
 hierarchy should be (-> @cBobeth)
  1. $EOS_TEST_PARAMETERS
  2. $EOS_HOMES/parameters
  3. use default as installed in $(pkgdatadir)/parameters

- [ ] create small python script ``eos-prepare-user`` to create, update and inspect parameter sets in the user's homedir ( -> @dvandyk)

- [ ] create wcxf script to translate a wcxf sector's wcs into a single EOS parameters .yaml file (-> @DavidMStraub)

**Comment by DavidMStraub** [comment]
Questions on last item.

- what to do with the `min`, `max` keys? Set them equal to `central`?
- what is the scale?
- is LFU assumed for b->u?
- The NP contributions from wcxf have to be added to the SM contributions from the default EOS input. So either the default EOS input must be put into the wcxf package (and updated when EOS is updated), or the script must take both the wcxf file and the EOS parameter file as input. What is preferable?

**Comment by dvandyk** [comment]
> - what to do with ``min``, ``max`` keys? Set them equal to central?

Yes please.

> - what is the scale?

For bsll the scale is fixed at mu = 4.2 GeV.

> - is LFU assumed for b->u?

Currently yes!

> - The NP contributions from wcxf have to be added to the SM contributions from the default EOS input. > So either the default EOS input must be put into the wcxf package (and updated when EOS is
> updated), or the script must take both the wcxf file and the EOS parameter file as input. What is 
> preferable?

These should be read from the parametres in the base EOS installation directory, which defaults to ``/usr/share/eos``.
