### ISSUE TITLE
Allow to specify base directory for GSL

### ISSUE THREAD

**Issue by daritter** [eos/eos#33]
Currently EOS assumes the gsl is installed in the default include path. It would be nice if we can specify a different prefix for gsl without manually providing -I and -L flags. 

This might also apply for hdf5 and fftw

**Comment by dvandyk** [comment]
> Currently EOS assumes the gsl is installed in the default include path. It would be nice if we can specify > a different prefix for gsl without manually providing -I and -L flags. 

Should be fixed now based on commit f5c0889765befc4bcbf5289d46bd0aea9c76a77a.

> This might also apply for hdf5 and fftw

There already is ``--with-hdf5''. Adding the same for FFTW now.
