### ISSUE TITLE
Header files missing from installation

### ISSUE THREAD

**Issue by michalkreps** [eos/eos#39]
Dear Danny. 

One of my students recently realised that when EOS is installed to a directory different from the one used to compile it by "make install" some header files in rare-b-decays subdirectory are missing. I think problem is that in eos/eos/rare-b-decays/Makefile.am on lines 30-42 not all header files are listed. I believe missing ones are lambda-b-to-lambda-dilepton.hh and long-distance.hh. I'm sure the first one should be copied, for the second one, I do not know.

Regards,

  Michal

**Comment by dvandyk** [comment]
@michalkreps Thanks. I see the problem. Will commit a fix ASAP!
