### ISSUE TITLE
Potentially missing isospin factor in B^- ->pi^0 l^- nubar

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#401]
I think a factor of 1/sqrt(2), as applied in the B->Vlnu case, is missing for B->Plnu.
@DomLeljak Could you please check and, if indeed missing, fix it?

**Comment by DomLeljak** [comment]
Please check 6fcde5c825aadc1488d6a9c90776f38b894d36c1, and for the test case 1b51aa6a3dee92caaa98e16edf7864a0adfb1397.
