### ISSUE TITLE
Rough edges use case docs

### ISSUE THREAD

**Issue by fredRos** [eos/eos#412]
I feel like a new user and in following the tutorial at https://eos.github.io/doc/use-cases.html#parameter-inference, I noticed a couple of rough edges that need some polishing. I will create a separate comment for each

**Comment by fredRos** [comment]
The docs say:

> The following examples are also available as an interactive Jupyter notebook

but what they should add is that the snippets assume a notebook and don't work in the terminal

```
>>> display(eos.Observables())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'display' is not defined

display(eos.Observables())
```

**Comment by fredRos** [comment]
The example `analysis_args` and description are not correct:

```diff
analysis_args = {
    'global_options': { 'form-factors': 'BSZ2015', 'model': 'CKMScan' },
    'priors': [
-        { 'parameter': 'CKM::abs(V_cb)', 'min':  38e-3, 'max':  45e-3, },
+        { 'parameter': 'CKM::abs(V_cb)', 'type': 'flat', 'min':  38e-3, 'max':  45e-3, },
```

```diff
- In the above, each prior is by default a uniform
+ In the above, each prior is a uniform
```

**Comment by fredRos** [comment]
There is a warning when the constraint is constructed and it seems useless:

```python
    'global_options': { 'form-factors': 'BSZ2015', 'model': 'CKMScan' },
...
    'likelihood': [
        'B->D::f_++f_0@HPQCD:2015A',
```

leads to 

```console
@1636320578: [WARNING [MultivariateGaussianConstraintEntry.make]] [MultivariateGaussianConstraintEntry.make] Constraint 'B->D::f_++f_0@HPQCD:2015A' in observable 'B->D::f_+(q2)' provides option key 'form-factors' with value 'BSZ2015'; user is overriding this preset with 'BSZ2015'
```

I'm not sure if I could omit the `global_option` and it would be the same, so I suggest that the factory function checks for identity of options before issuing a warning

**Comment by fredRos** [comment]
> We carry out preruns = 5 burn-in runs/preruns

This is confusing. It should say: 5 chains are run in parallel with a prerun length...

then refer to pypmc for details

**Comment by fredRos** [comment]
The last image https://eos.github.io/doc/images/use-cases_simulation_hist2d-0-3.png is not available. Is that a temporary broken link?

**Comment by mreboud** [comment]
Thank you @fredRos for the feedback, we usually update the doc and the code simultaneously but it appears that we missed a couple of things there...

**Comment by mreboud** [comment]
Thank you @fredRos for the feedback, we usually update the doc and the code simultaneously but it appears that we missed a couple of things there...

**Comment by mreboud** [comment]
> The docs say:
> 
> > The following examples are also available as an interactive Jupyter notebook
> 
> but what they should add is that the snippets assume a notebook and don't work in the terminal
> 
> ```
> >>> display(eos.Observables())
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'display' is not defined
> 
> display(eos.Observables())
> ```

I don't really understand this comment. We provide an `.ipynb` file which, by definition, is intended to be run interactively. If the user wants to run this notebook as a python script, they do need to get rid of the `display`s, but this is not something that EOS has to provide, is it?

**Comment by dvandyk** [comment]
> I don't really understand this comment. We provide an `.ipynb` file which, by definition, is intended to be run interactively. If the user wants to run this notebook as a python script, they do need to get rid of the `display`s, but this is not something that EOS has to provide, is it?

Fred's point is that we do not say that the code in the documentation is meant for Jupyter notebooks only. This fact should be stated somewhere.

**Comment by mreboud** [comment]
> > I don't really understand this comment. We provide an `.ipynb` file which, by definition, is intended to be run interactively. If the user wants to run this notebook as a python script, they do need to get rid of the `display`s, but this is not something that EOS has to provide, is it?
> 
> Fred's point is that we do not say that the code in the documentation is meant for Jupyter notebooks only. This fact should be stated somewhere.

Ah I understand now! Will do this.

**Comment by fredRos** [comment]
> Thank you @fredRos for the feedback, we usually update the doc and the code simultaneously but it appears that we missed a couple of things there...

@dvandyk @mreboud 
If you want to partially solve this problem permanently, you have to extract the snippets from the python notebook and run an automated test  to ensure that the whole notebook produces the right output. 

But this  still leaves one manual part: proofreading the text to describe the snippets. Make this part of your release validation workflow and you can be sure you are shipping code with proper docs!

**Comment by mreboud** [comment]
> @dvandyk @mreboud If you want to partially solve this problem permanently, you have to extract the snippets from the python notebook and run an automated test to ensure that the whole notebook produces the right output.
> 
> But this still leaves one manual part: proofreading the text to describe the snippets. Make this part of your release validation workflow and you can be sure you are shipping code with proper docs!

I agree that this would benefit from being automatized, but as you say, the conversion is non trivial (cf. also tables, plots...). We discussed that already, but did not find a satisfactory solution yet...
