### ISSUE TITLE
B->D{e,mu}nu plot in the inference notebook

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#419]
@MartinJung1978 is suspicious of the datasets and/or posterior shown in the plot. Prior to 1.0 release, we should make doubly sure that the shown curves and data points are correct.

**Comment by mreboud** [comment]
Do your have more information on what may be wrong?

**Comment by MartinJung1978** [comment]
The fit looks horrible, as if it weren't describing the data well at all (I know the chi2 is reasonable). A BGL fit to the same data looks much better (https://arxiv.org/pdf/1606.08030.pdf , still looks a bit biased towards smaller values though, which might be due to d'Agostini...) So I was wondering if there was an issue.

**Comment by mreboud** [comment]
Ok thanks a lot, I will have a look

**Comment by dvandyk** [comment]
> The fit looks horrible, as if it weren't describing the data well at all (I know the chi2 is reasonable). A BGL fit to the same data looks much better (https://arxiv.org/pdf/1606.08030.pdf , still looks a bit biased towards smaller values though, which might be due to d'Agostini...) So I was wondering if there was an issue.

Keep in mind that the fit shown in the example is not using the unitarity bounds in any way. The best-fit point here might easily violate the bounds.

**Comment by DomLeljak** [comment]
Maybe my hunch is wrong here, but what is the default model in the fit? I remember copying the code a long time ago and getting a bad fit, which was fixed by changing the model to `CKMScan`. I guess the default was `SM`?

**Comment by DomLeljak** [comment]
> Maybe my hunch is wrong here, but what is the default model in the fit? I remember copying the code a long time ago and getting a bad fit, which was fixed by changing the model to `CKMScan`. I guess the default was `SM`?

Nope, this wasn't it.

**Comment by DomLeljak** [comment]
Maybe:

`'rescale-by-width': True`

:D

**Comment by dvandyk** [comment]
@DomLeljak I could kiss you, if there were no pandemic going on! You are spot on!

![plot](https://user-images.githubusercontent.com/42914/141646309-cdec7ffe-24b1-49b3-84fd-5290665764a6.png)

@MartinJung1978 looks much better, doesn't it? Was a pure plotting problem. When comparing to the differential branching ratio, we need to divide the bin-integrated BR by the bin's width. Thanks for catching this!

**Comment by MartinJung1978** [comment]
Perfect, that looks much better :-)
