### ISSUE TITLE
eos/parameters/b-to-c-cc.yaml not installed

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#42]
`make distcheck` presently fails with the following error:
```
Running test case 'wcm_make_test'
Test case threw exception: Unknown parameter: 'b->clnu::Re{cSL}'
Running test case 'wilson_coefficients_b_to_s_test'
Test case threw exception: Unknown parameter: 'b->clnu::Re{cSL}'
Running test case 'constrained_wilson_scan_model_test'
Test case threw exception: Unknown parameter: 'b->clnu::Re{cSL}'
```

Looking at [the eos/parameters/Makefile.am in the most recent commit](https://github.com/eos/eos/blob/05d1ccc4fce3eba8b825ab3495328c090f552035/eos/parameters/Makefile.am#L5), I see that the new parameters `b-to-c-cc.yaml` are not included in the list of installable files.
@akokulu7 Can you fix this please?

**Comment by akokulu7** [comment]
[parameters] b-to-c-cc.yaml included in the list of installable files.

**Comment by dvandyk** [comment]
@akokulu7 Thanks Ahmet! FYI, you can refer to your repo like this: akokulu7/eos@620d4ad0262242fe45a53ef161d1c595bf3364e8 . Your commit seems to fix the problem. However, you did not base it on the most recent commit in the master branch. I rebased it, and removed the whitespace problem (spaces instead of tabs; makefiles do distinguish between them). The automated tests for dvandyk/eos@b88d2f1a2d570bbd27d877d87f1d83d9e05513b2 are running now.
