### ISSUE TITLE
Trouble installing libpmc

### ISSUE THREAD

**Issue by fredRos** [eos/eos#43]
Following the manual in trying to install from source, I did not succed.
```
mkdir /tmp/libpmc
pushd /tmp/libpmc
wget http://www2.iap.fr/users/kilbinge/CosmoPMC/pmclib_v1.01.tar.gz
tar zxf pmclib_v1.01.tar.gz
pushd pmclib_v1.01
./waf configure --m64 --prefix=$SWMOD_INST_PREFIX

bunzip2: Data integrity error when decompressing.
        Input file = t.bz2, output file = t

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

bunzip2: Deleting output file t, if it exists.
Error: Waf cannot be unpacked, check that bzip2 support is present
```

I tried downloading and unpacking twice and got the same `bzip` error again. So I don't believe in an evil bit flipping error. The hard but clean solution would be to remove the dependency on pmclib and implement the few function that are needed by myself. 

That would make the installation experience easier for everyone

**Comment by dvandyk** [comment]
I cannot reproduce the problem right now. However, I completely agree with the proposed solution.
