### ISSUE TITLE
Clean utils

### ISSUE THREAD

**Issue by mreboud** [eos/eos#443]
A couple of pieces of code are now in the standard library or not used anymore. We should be able to remove:
  - [x] `utils/accumulator.{cc.hh}`
  - [x] `utils/apply.{cc,hh}`
  - [ ] `utils/observable_stub.{cc,hh}` <-- to be replaced by the expression parser?
  - [ ] #479

We can also move:
  - [ ] `utils/lcda.{cc,hh}` -> @SKuerten

**Comment by dvandyk** [comment]
@SKuerten can you move ``utils/lcda{.hh,.cc,_TEST.cc}`` to  ``form-factors/`` and adapt all call sites?
