### ISSUE TITLE
Charged leptonic B decays

### ISSUE THREAD

**Issue by DomLeljak** [eos/eos#450]
Three brief comments:

1. There should probably either be a separate `.yaml` file for the charged leptonic decay constraints (currently they're in `constraints/Bq-to-ll.yaml`), e.g. `Bq-to-lnu.yaml`, or the existing name of the file should be adapted?
2. The reference for the `B^+->tau^+nu::BR@Belle:2015A` constraint is wrong. Actually, it should be added and changed in the constraint name.
3. The expression for the decay width in `b-decays/b-to-l-nu.cc` will fail for massless leptons, as the `m_l` parameter is in the denominator (line 120).

All of these are by me, so I'll fix them, I just need input on 1, @dvandyk.

**Comment by mreboud** [comment]
1. You can change the name of the yaml file to `Bq-to-dilepton.yaml`
2. Indeed.
3. We already have this issue elsewhere in the code. In this case we ask the user to provide a non-zero lepton mass, even if it is very small. A error should be raised if the mass is set to zero.

**Comment by DomLeljak** [comment]
For 3., the expression can be fixed as Danny suggested, just pull the `m_l` from the normalization (line 118) and push it to the bracket in line 120.

**Comment by mreboud** [comment]
This will definitely be better than raising an error indeed
