### ISSUE TITLE
`make_signal_pdf` doesn't accept `IntermediateResult`

### ISSUE THREAD

**Issue by mreboud** [eos/eos#458]
This prevents the normalizations as `integrated_branching_ratio` to take an `IntermediateResult` argument.

**Comment by dvandyk** [comment]
From the meeting: add a new signature to ``make_signal_pdf`` that takes ``evaluate``, ``prepare`` and ``normalization``, and calls ``prepare`` before each call to ``normalization``.

**Comment by dvandyk** [comment]
Fix included in #395.
