### ISSUE TITLE
[python/.../plotter.py] Consistency in documentation

### ISSUE THREAD

**Issue by cBobeth** [eos/eos#476]
1)

https://github.com/eos/eos/blob/3e0d1e2723adbeb452e521e8f17e7d25f9294348/python/eos/plot/plotter.py#L1373

Would'nt it be better to write: "... Defaults to ``[68, 95, 99]``." to be consistent with the actual usage?

2)

This optional argument

https://github.com/eos/eos/blob/3e0d1e2723adbeb452e521e8f17e7d25f9294348/python/eos/plot/plotter.py#L1319

could be added to the documentation here:

https://github.com/eos/eos/blob/3e0d1e2723adbeb452e521e8f17e7d25f9294348/python/eos/plot/plotter.py#L1252

**Comment by mreboud** [comment]
@cBobeth I agree, can you create a PR if you have time?

**Comment by cBobeth** [comment]
I can create a pull request.

**Comment by mreboud** [comment]
Closed by #480
