### ISSUE TITLE
`dim` vs. `dof`

### ISSUE THREAD

**Issue by mreboud** [eos/eos#477]
I think that there is an ambiguity between `dof` and `dim` in the constraints. For e.g. a `MultivariateGaussian`:

- `dim` should be the number of observables = dimension of all the entries: means, kinematics, options...
- `dof` should only reflect the number of underlying measurements but is a priori not fixed.

E.g. for an angular analysis, `dim` = `dof` = number of angular observables.
Now, suppose that I concatenate several observables in one Gaussian constrain, I would like to have `1 = dim < dof`. Does this make sense?

**Comment by dvandyk** [comment]
As discussed offline, there are cases where `dof < dim`, e.g., in presence of no-orthogonal response matrix.

I would
 - [ ] infer `dim` from the length of the mean;
 - [ ] remove `dim` from the data files;
 - [ ] make `dof` optional in all constraint types and default to `dim`;
 - [ ] remove `dof` form constraints if `dof == dim`.

**Comment by mreboud** [comment]
@Danny I am still a bit lost with the cases where `dim != dof`, is this example wrong:
https://github.com/eos/eos/blob/67e71842cb2e1e41e4a623432d9303ccb9782cf2/eos/constraint_TEST.cc#L610-L630
If yes, what would be the correct values according to you? `dof` is only used to compute the test statistics, correct?

**Comment by mreboud** [comment]
> Hi Meril, as far as I remember, the original intention to distinguish 'dim' and 'dof' was that some constraints in a multivariate Gaussian, like constraints on parameters deriving from theory, contrary to real measurements, should not enter as 'dof' when calculating goodness-of-fit criteria like "chi^2/dof" etc. See for example explanations around eq. (IV.2) in https://arxiv.org/pdf/1310.2478.pdf But maybe things have changed meanwhile or maybe I just do not remember correctly. Best wishes, Christoph.

Thank you Christoph for the reference and the reply, it helps. The plan was to simplify this a bit, it seems to me that `dim` is always the number of measurements (`means`), but `dof` can be anything smaller than `dim`.
The example I gave was not the correct one, in the case of a non-orthogonal response matrix, one can also have `dim != dof` it seems, but this doesn't appear in the example...

**Comment by dvandyk** [comment]
The 2017 Belle data on ``B->D^*lnu``, for example, require a response matrix to "forward fold" the theory expressions to the detector level observables. Such a matrix need not be square, and can lead to ``dof`` theory expressions being challenged by ``dim`` observations.

**Comment by mreboud** [comment]
Ok so I can remove `dim` entirely, fix it to the length of `means` and keep `dof` optional, right?

**Comment by mreboud** [comment]
Their are a couple of remaining cases were `dof` was set to zero, I don't know if this was really on purpose... One was added by me, I a must admit that I know no good reason to keep `dof=0` in this case.

- https://github.com/eos/eos/blob/67aa0916a26270d0fe8bb3e08b534160e7bef4bf/eos/constraints/Lb-to-Lq-form-factors.yaml#L373
- https://github.com/eos/eos/blob/67aa0916a26270d0fe8bb3e08b534160e7bef4bf/eos/constraints/Lb-to-Lq-form-factors.yaml#L454
- https://github.com/eos/eos/blob/67aa0916a26270d0fe8bb3e08b534160e7bef4bf/eos/constraints/B-to-V-form-factors.yaml#L1288
- https://github.com/eos/eos/blob/67aa0916a26270d0fe8bb3e08b534160e7bef4bf/eos/constraints/B-to-V-form-factors.yaml#L1308
- https://github.com/eos/eos/blob/67aa0916a26270d0fe8bb3e08b534160e7bef4bf/eos/constraints/B-to-V-form-factors.yaml#L1328
