### ISSUE TITLE
[rare-b-decays] Hard-coded lepton flavor in `b-to-ll.cc` ?

### ISSUE THREAD

**Issue by cBobeth** [eos/eos#484]
In this line it looks like as if the lepton flavour of the Wilson coefficients is hardcoded as "mu"

https://github.com/eos/eos/blob/0738b58023cbd6ca23105c58ed90bd0f793bb9ee/eos/rare-b-decays/b-to-ll.cc#L106

Is'nt it?

If so, how to fix it? Is the most recent way to handle lepton-flavour this  `LeptonFlavorOption`? How does it work?

**Comment by dvandyk** [comment]
> In this line it looks like as if the lepton flavour of the Wilson coefficients is hardcoded as "mu"
Indeed, and that is a bug.

> If so, how to fix it? Is the most recent way to handle lepton-flavour this `LeptonFlavorOption`? How does it work?
Easiest way is to use ``opt_l.value()`` rather than ``"mu"``, I think.

We are tracking the conversion to the new ``Model`` interface in #418, but this is different and should be fixed earlier.
@cBobeth thanks for spotting this!

**Comment by cBobeth** [comment]
Actually the thanks go to Arturo de Giorgi for spotting this. I will try to fix using `opt_l.value()` then.

**Comment by dvandyk** [comment]
He needs a Github and Discord account to report this directly! :smile:
