### ISSUE TITLE
Improve errors and messages in `Observables::insert`

### ISSUE THREAD

**Issue by mreboud** [eos/eos#489]
For the moment, a failed insertion is just reported as `Could not create expression ...`. This can happen for several reasons including the fact that the observable already exists. I think that improving the output in this case and maybe catching this specific error may be beneficial.

**Comment by dvandyk** [comment]
- when inserting/overwriting an existing observable, issue a warning via ``Log``
 - only throw a C++ exception when "a real issue" arises
