### ISSUE TITLE
Parametric-only likelihoods should lead to early abort of the computation likelihood

### ISSUE THREAD

**Issue by mreboud** [eos/eos#492]

**Comment by dvandyk** [comment]
In #8 we already stop the likelihood evaluation early. However, all observables must be computed (by the ``ObservableCache``) prior to calculating the likelihood. They only way around this would be to create a data structure internally that tracks which observables belong to which ``LogLikelihoodBlock``. But that seems an intractable problem, when taking together with the ``CachedObservable`` and so on.
