### ISSUE TITLE
Split ``eos/form-factors/mesonic-impl.hh`` into individual files

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#499]
New files should follow the existing naming convention ``parametric-XYZYEAR{-impl.hh,.hh,.cc,_TEST.cc}``.

**Comment by dvandyk** [comment]
Determine outcome:
 - [ ] ``MvD2016`` (baryon)

Keep and split out
 - [ ] ``BCL2008`` (meson)
 - [ ] ``KMPW2010`` (meson)
 - [ ] ``BSZ2015`` (meson)
 - [ ] ``DKMR2017`` (baryon)
 - [ ] ``HQET`` (meson rename -> ``BGJvD2019``)
 - [ ] ``HQET`` (baryon rename -> ``...``)
 
Remove:
 - [ ] ``BZ2004`` (both of them, ``P->P`` and ``P->V``)
 - [ ] ``BFW2010`` (meson)
 - [ ] ``FMvD2015`` (meson)

**Comment by mreboud** [comment]
What about `FvDV2018` (P->PP)?
