### ISSUE TITLE
python warnings

### ISSUE THREAD

**Issue by fredRos** [eos/eos#50]
Use standard module in all python code https://docs.python.org/3/library/warnings.html

**Comment by dvandyk** [comment]
We should also automatically forward ```Log::message``` to standard error. I guess we can do
this in ```eos/__init__.py``` ?

**Comment by fredRos** [comment]
related: what do you currently do if EOS C++ code throws an exception? We can easily translate that into a custom python exception, see [here](http://www.boost.org/doc/libs/1_48_0/libs/python/doc/v2/exception_translator.html)

**Comment by fredRos** [comment]
> We should also automatically forward Log::message to standard error. I guess we can do this in eos/__init__.py ?

You mean via 

            void set_log_stream(std::ostream *);

Why do you want to print info on `stderror`? I see you set `std::cerr` as the default stream in eos but why not `stdout`? 

Anyways, since `cerr` is the default, we would not have to change anything in python
