### ISSUE TITLE
Output in analysis tasks with Jupyter

### ISSUE THREAD

**Issue by mreboud** [eos/eos#508]
When using tasks in a jupyter notebook the ouput cells are not scrallable and the entire output is not shown:
![Screenshot from 2022-05-31 11-31-50](https://user-images.githubusercontent.com/24250382/171142692-e51e2053-2415-492a-a76a-489eacee3a30.png)

**Comment by pluegh** [comment]
The bug is probably caused by a missing argument [here](https://github.com/eos/eos/blob/729ece7062ab17fb0ba00afbe69c5de308cfe1de/python/eos/tasks.py#L68).

It should be `ioutput = _ipywidgets.Output(layout={'height': '200px', 'overflow': 'auto'})`.
