### ISSUE TITLE
Duplicate entry in ``eos/parameters/hadronic-matrix-elements.yaml``

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#523]
The following code only works due to a quirk in how ``yaml-cpp`` parses the file:
https://github.com/eos/eos/blob/7bdac93e3f0bef1227d7dae5afe80891661c8c81/eos/parameters/hadronic-matrix-elements.yaml#L4359-L4376

The key to both entries is identical. It is ambiguous if only the first or only the second entry should persevere. Certainly not both.
(Detected by running ``yamlfmt`` on the source tree in preparation of a YAML formatting and linting pre-commit hook.)

**Comment by mreboud** [comment]
They are only similar before the expansion is applied, so it shouldn't be a problem since the expansion parameters are different.

**Comment by dvandyk** [comment]
However, ``yaml-cpp`` is not required to pass both entries on to EOS. It can disregard one. And the entry visible to EOS is not guaranteed to be always the same entry, either.

**Comment by mreboud** [comment]
Ok, so you think it would be safer to change, say, the second one, by e.g. adding the `A` of `Arg` and `Abs` to the name?

**Comment by dvandyk** [comment]
That would work, yes!
