### ISSUE TITLE
Useless warning message in the tests

### ISSUE THREAD

**Issue by mreboud** [eos/eos#529]
Due to the commit c7cd161fda7ab045f0021fab3fe8d71092c44e43, we now have an annoying and useless message when testing:
```[WARNING [ObservableEntries.insert_or_assign]] Entry for observable test::obs1 has been replaced.```

This comes from this line https://github.com/eos/eos/blob/c7cd161fda7ab045f0021fab3fe8d71092c44e43/test/test.cc#L117
Can we fix that by e.g. protecting the insertion in an `#ifndef` C++ statement so that it happens only once?

**Comment by mreboud** [comment]
In fact there is a bug in c7cd161, the warning appears even if the expression observable is inserted for the first time. So this is not related to `test.cc`.

**Comment by dvandyk** [comment]
From [C++ reference](https://en.cppreference.com/w/cpp/container/map/insert_or_assign):
```
Return value
1,2) The bool component is true if the insertion took place and false if the assignment took place. The iterator component is pointing at the element that was inserted or updated.
```
That's the same logic as for ``insert``. I somehow thought the logic was inverted. Can you fix this?

**Comment by mreboud** [comment]
Sure, asap
