### ISSUE TITLE
File name in yaml-cpp error

### ISSUE THREAD

**Issue by fnovak42** [eos/eos#561]
When a yaml-cpp error occurs, the problematic file is not printed, e.g.
 ```RuntimeError: yaml-cpp: error at line 45, column 5: end of map not found```
Printing the name of the file would simplify debugging.

**Comment by mreboud** [comment]
@dvandyk What about printing a comment line such as `"Now reading file " + file` in this function:
https://github.com/eos/eos/blob/924dc161ba5cfd8984710ea8cb0d57daf5e2ef22/eos/constraint.cc#L2288-L2323
