### ISSUE TITLE
Phase space only form-factors

### ISSUE THREAD

**Issue by mreboud** [eos/eos#569]
A phase-space implementation of the form-factors (form-factors identically equal to unity) could be useful for comparison with experimental MC.

**Comment by mreboud** [comment]
It is probably slightly more complex than that, since "phase-space only" usually means that the spin structure is not accounted for...
@dvandyk maybe we can close this issue...

**Comment by dvandyk** [comment]
> It is probably slightly more complex than that, since "phase-space only" usually means that the spin structure is not accounted for... @dvandyk maybe we can close this issue...

Since there does not seem to be an agreed-upon definition of what experimental MCs mean by "phase-space only", let's not mess with this.
