### ISSUE TITLE
WET test cases do not compare SM values using default parameters

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#575]
While discussing #571 with @mreboud we noticed that the test cases checking for the identity of the SM values and the WET parameters erroneously do not use the default parameters:
https://github.com/eos/eos/blob/4040eb54223b55da602c0de9e66d7ca97bc1d4a1/eos/models/wet_TEST.cc#L286

_Originally posted by @dvandyk in https://github.com/eos/eos/issues/571#issuecomment-1385097227_

**Comment by lorenzennio** [comment]
Good point. I just ran the test after changing this, and then it fails due to a difference in cVL. This is exactly the issue we discussed with @mreboud. Should I open a PR for this?

**Comment by mreboud** [comment]
Let me see if I understand the problem. This test ensures that the WC are the same in the `WET` and `SM` models. So it boils down to a consistency check between the value of `sbnunu::Re{cVL}` and some default parameters. For the moment, these parameters are set to some `reference_parameters` which differ from the default ones.

If I remove the `reference_parameters` as you suggest, I have to change the value of `sbnunu::Re{cVL}` to match EOS default parameters. And this will need to be done each time we update EOS default parameters. Is that what you want?
