### ISSUE TITLE
Incompatibility with numpy v1.24

### ISSUE THREAD

**Issue by cbolognani** [eos/eos#576]
np.float is not supported anymore for v>=1.24

**Comment by mreboud** [comment]
Thanks for reporting!
As far as I see, `np.float` is only used in these two lines 
https://github.com/eos/eos/blob/4040eb54223b55da602c0de9e66d7ca97bc1d4a1/python/eos/plot/plotter.py#L861-L862

It can safely be replaced by `np.double`.
