### ISSUE TITLE
Refactoring of `signal_pdf`

### ISSUE THREAD

**Issue by mreboud** [eos/eos#610]
- [ ] Move `signal_pdf.{cc,hh}` to a dedicated directory
- [ ] Move `make_signal_pdf_entries()` to a separate file and maybe split it into subfiles corresponding to the decay type
- [ ] Harmonize the kinematic names

@dvandyk what do you think?
@pluegh you wanted to look at this?

**Comment by dvandyk** [comment]
I agree that this needs some tidying up. But I would like to structure it similar to what he have for the observables, i.e.:
  - self-documenting;
  - store close to the code (i.e., ``B->Dlnu::P(q2)`` should be in ``eos/b-decays/signal-pdf.cc``.
  
For that purpose, we have would need
 - [ ] ``SignalPDFSection``: contains one or more groups of signal PDFs, e.g., all signal PDFs within ``eos/b-decays``;
 - [ ] ``SignalPDFGroup``: contains one or more signal PDF entries, e.g., all signal PDFs corresponding to the process ``B->Dpilnu``;
 - [ ] ``SignalPDFEntry``: describes a single signal PDF;
 - [ ] ``SignalPDFs``: contains all sections, is accessible by the user, can iterate over all sections and all entries.
 
 A lot of this is copy&paste from ``eos/observable.{hh,cc}`` and find&replace.
