### ISSUE TITLE
Conversion of HQET form factors disagrees with literature (arXiv:1309.0301)

### ISSUE THREAD

**Issue by peterstangl** [eos/eos#625]
The conversion of the HQET form factors $h_{T_1}$, $h_{T_2}$ and $h_{T_3}$ to $T_3$ seems to disagree with Eq. (39) in [arXiv:1309.0301](https://arxiv.org/abs/1309.0301). In particular, it looks like a factor `-2` is missing in the term proportional to $h_{T_3}$ (`_h_t3(q2)`) in

https://github.com/eos/eos/blob/417d909b35f7eac3b1ac7b6a552ff68aa20ff41d/eos/form-factors/mesonic-hqet.hh#L1298

It is not clear to me whether this is a typo in EOS or in [arXiv:1309.0301](https://arxiv.org/abs/1309.0301), or whether both use different conventions.

**Comment by peterstangl** [comment]
This issue was noticed when comparing `flavio` and `EOS` in the context of https://github.com/flav-io/flavio/issues/156.

**Comment by dvandyk** [comment]
@peterstangl sorry for not being able to discuss this in person with you. Meeting on Friday with @MartinJung1978, and hope to address this issue then and there.

**Comment by dvandyk** [comment]
@peterstangl Found an opportunity to discuss and compare with @MartinJung1978. Martin has in his notes that there is a different notation for h_T3 in the paper of Datta and arxiv:1309.0301. He has explicitly a factor of -1/2, which is correctly applied in the EOS code.

**Comment by mreboud** [comment]
Shouldn't we contact the authors of 1309.1301 at that point?

**Comment by dvandyk** [comment]
We are not sure that 1309.1301 is incorrect. This is a problem of definition and consistency. Their result can be consistent due to a different convention for h_T3.

**Comment by peterstangl** [comment]
Thanks a lot @dvandyk and @MartinJung1978 for checking this!

As far as I see, 1309.1301 defines h_T3 in their Eq. (46b) together with h_T1 and h_T2, which should fix their convention. Do you have a similar expression or a reference that you use, where your convention is fixed? Then one could do a direct comparison in the literature to see if it's really a matter of convention or possibly a typo somewhere.

**Comment by peterstangl** [comment]
I learned from @mbordone (thanks a lot!) that your convention is based on 1703.05330. The definition of h_T3 in Eq. (11e) of 1703.05330 differs by a factor -2 from its definition in Eq. (46b) of 1309.0301, i.e.
```
h_T3^(1703.05330) = -2 h_T3^(1309.0301)
```
So it seems that these two different conventions can fully explain the different results.
