### ISSUE TITLE
B_s->K^*lnu does not use the common codebase for B->Vlnu processes

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#635]

**Comment by dvandyk** [comment]
- [ ] Check if there are any observables that the existing ``B_s->K^*lnu``-specific code provides that our generic ``B->Vlnu`` code does not.
 - [ ] Replace references to ``BsToKstarLeptonNeutrino`` with ``BToVectorLeptonNeutrino``

**Comment by cbolognani** [comment]
Sorry, it escaped my mind! Finally looked back at this: 

For the K*, there are transverse asymmetries A and transversity observables H, defined in BHvD 1006.5013 and BS 1106.3283 which are not defined for generic Vlnu decays. Paying attention to notation, the asymmetries which are already coded for generic Vlnu decays do not seem to correspond to the ones for K*lnu.

I could implement these in terms of the already defined J-like coefficients, both differential and integrated, in ```b-to-vec-l-nu.cc``` , copying from the existing code in ```bs-to-kstar-l-nu.cc```

**Comment by dvandyk** [comment]
> Sorry, it escaped my mind! Finally looked back at this:
> 
> For the K*, there are transverse asymmetries A and transversity observables H, defined in BHvD 1006.5013 and BS 1106.3283 which are not defined for generic Vlnu decays. Paying attention to notation, the asymmetries which are already coded for generic Vlnu decays do not seem to correspond to the ones for K*lnu.
> 
> I could implement these in terms of the already defined J-like coefficients, both differential and integrated, in `b-to-vec-l-nu.cc` , copying from the existing code in `bs-to-kstar-l-nu.cc`

@cbolognani Thanks for looking into this. I think we can get rid of the the transverse asymmetries A_T^i and the observables H_T^i. So don't worry about those. And I think the observables R_{long,perp,para} are better dealt with as expression observables; I would remove them from the default set of observables as well.

What would interest me is if the existing test cases pass once the underlying codes are switched over.

**Comment by lorenzennio** [comment]
Resolved by #909
