### ISSUE TITLE
Question on EOS vs Flav-io comparisson

### ISSUE THREAD

**Issue by gkaratha** [eos/eos#650]
Dear experts,

My name is George Karathanasis and I am working on the dBF/dq2 measurement of the B->mmK decay for the CMS experiment. The last step of the analysis, is to compare the measurement with few theoretical models. Therefore, I found this package and assuming you have no issue to use it (with the proper citations of course),  I would like to ask couple of questions:
1) I read the documentation, and tried to write a EOS code. Since is a public analysis I want to make sure my code is correct. Here is my code[*]. Do you think there is anything wrong with it? I am not certain about the tags because I found them looking in the code itself.
2) Can you help me get the uncertainty?
3) I compared the result with "Flav-io" a different package. The difference is large (see attached). *IF* my EOS code has no bugs, is there an explanation for the difference? Thanks a lot in advance.

Best regards, 
George Karathanasis

[*] import eos
from IPython.display import display
import numpy as np
#import ROOT as rt

Produce_weights=True

parameters = eos.Parameters.Defaults()

#display(parameters["mass::K_u"].min())
kins1 = eos.Kinematics(q2_min=0.1, q2_max=9.00)
opts1 = eos.Options(model='WET',l="mu",tag="BFS2004",q="u")
#obs1 = eos.Observable.make('B->Kll::BR', parameters, kins1, opts1)
kins2 = eos.Kinematics(q2_min=0.1, q2_max=15.00)
opts2 = eos.Options(model='WET',l="mu",tag="GvDV2020",q="u")
obs2 = eos.Observable.make('B->Kll::BR', parameters, kins2, opts2)
kins3 = eos.Kinematics(q2_min=15.0, q2_max=22.00)
opts3 = eos.Options(model='WET',l="mu",tag="GP2004",q="u")
obs3 = eos.Observable.make('B->Kll::BR', parameters, kins3, opts3)
print(obs2.evaluate()+obs3.evaluate())
total_BF=obs2.evaluate()+obs3.evaluate()

dBF_dq2=[]
output=""
for idx in range(0,66):
    if idx==0: q2min=0.1
    else: q2min=float(idx*(22.0-0.1)/66.0)
    q2max=(float(idx)+1.0)*(22.0-0.1)/66.0
    #if idx<8: tag="BFS2004"
    if idx/66.<15./22.: tag="GvDV2020"
    else: tag="GP2004"
    kin_dif = eos.Kinematics(q2_min=q2min, q2_max=q2max)
    opts_dif = eos.Options(model='WET',l="mu",tag=tag,q="u")
    obs = eos.Observable.make('B->Kll::BR', parameters, kin_dif, opts_dif)
    output+="bin "+str(idx)+" range: "+str(q2min)+","+str(q2max)+" dBF "+str(obs.evaluate())+" norm "+str(obs.evaluate()/total_BF)+"\n"
    dBF_dq2.append(obs.evaluate())
    print("bin",idx,"range:",q2min,",",q2max,"dBF=",obs.evaluate(),"norm=",obs.evaluate()/total_BF)
![Screenshot from 2023-06-14 18-34-44](https://github.com/eos/eos/assets/17452912/a6c50b06-d8b1-44c0-82a8-cafea5e18aa5)

**Comment by mreboud** [comment]
Hi George, thanks for your question! EOS is precisely developed for this kind of usage, so you are at the right place.

Let me start with this `tag`. To `B -> K mu mu` amplitude contains non-local contributions due to quark (mostly charm) loops. The role they play depends on q2, it is small below 6 GeV^2, very large around the `J/psi` and `psi(2S)` masses, and relatively small at large q2. The `tag` option allows you to choose the theory model you want to use for these contributions. `BFS2004` refers to [this paper](https://arxiv.org/abs/hep-ph/0412400) which uses QCD factorization, it is more reliable at small q2.

Choosing the correct tag highly depends on the experimental analysis, what is your q2 range? Do you also measure the BR at large q2? We can discuss that together.

**Comment by mreboud** [comment]
Now to your questions:

1.  Changing the `tag` as a function of q2 is definitely the thing to do. As I said however, these parameterizations come with uncertainties and their parameters need to be tuned. What you did is probably valid below 6 GeV^2 and above 16 GeV^2, but certainly not between these two regions (you would e.g. expect to see the J/psi and the psi(2S) peaks).

2. Yes. You have three main sources of uncertainties, the (local) form factors, the non-local contributions and, to a lesser extend, the CKM element. To get the uncertainties, you need to vary these parameters as in [this tutorial](https://eos.github.io/doc/predictions.html). You can discuss this further together.

3, I am not at all surprised by the difference with Flavio, the agreement is even rather good ^^ The default parameters value that we use for the form factors are different, this is enough to explain the shift you see at small q2.

**Comment by mreboud** [comment]
At that point we should probably continue the discussion by email on how to adapt this code to your needs. If you are happy with these answers, can you close the issue?

**Comment by gkaratha** [comment]
Dear @mreboud 

thanks a lot for this super detailed answer!! I would be more than happy to close this issue and continue via email. My email is georgios.karathanasis@cern.ch. Just to answer the first question we measure the dBF/dq2 in both low q2 region and high q2
regions. Also we have two bins between the resonances. Thanks a lot one more time for this detailed answer and the help.

Best regards,
George Karathanasis

![Screenshot from 2023-06-15 17-27-24](https://github.com/eos/eos/assets/17452912/31b5fe2a-a892-453e-9122-a8aad5c2afd0)
