### ISSUE TITLE
``GoodnessOfFit`` does not respect the ``begin`` and ``end`` options

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#652]
Reported by @cbolognani

**Comment by mreboud** [comment]
I am a bit surprised since this is something we used in the KMatrix project, isn't it @SKuerten?

**Comment by mreboud** [comment]
> I am a bit surprised since this is something we used in the KMatrix project, isn't it @SKuerten?

We were indeed fixing this, but the branch has not been merged yet: https://github.com/eos/eos/pull/538/commits/c28d7b6e532357c14f9e8185d0c34b83aa81422c

Thanks for the fix @dvandyk!
