### ISSUE TITLE
The `corner-plot` task should also support plotting posterior predictions

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#657]
Currently, only the distribution of the posterior samples can be plotted. It would be nice if we could repurpose the code to also plot posterior predictive samples as obtained using the `predict-observables` task.

**Comment by mreboud** [comment]
That would indeed be very useful!

**Comment by dvandyk** [comment]
Philip is working on this as of July 14th. @pluegh Can you comment on how this is progressing?

**Comment by pluegh** [comment]
This is mostly done, only the TeX labels for predicted observables have to be generated from the qualified names in a smart way. Unfortunately I cannot work on it today, nor is the code checked in somewhere.
