### ISSUE TITLE
Plotting user-defined observables

### ISSUE THREAD

**Issue by cbolognani** [eos/eos#663]
I am trying to plot form factors multiplied by their pole factors, but illustrating already existing EOS constraints is not doable for me. Is there an easy or standard solution to do this?

**Comment by dvandyk** [comment]
@mreboud Discussed today at the meeting. Suggested solution: permit to define a function of the x and y coordinates  in the plotting framework that rescales all content.

**Comment by dvandyk** [comment]
As discussed today, we probably want to create 2 new plot item types:
 - ``constraint-residuals``, inheriting from ``constraint``, which accepts additional information on a parameter point at which to evaluate the observable;
 - ``scaled-constraint``, inheriting form ``constraint``, which accepts additional information in form of an observable expression that multiplies every y value.

**Comment by mreboud** [comment]
This is implemented in #538
