### ISSUE TITLE
GSL{Vector,Matrix,RNG}Ptr

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#69]
Following the discussion of PR #66, it would be nice to use RAII for handling pointers to GSL objects.
Do we want something like here: https://github.com/dvandyk/eos/commit/b1c942737e00cac15c73791d8e7c61261be3297c ??

The only problem I see is that we would need either
 - to include ```gsl_rng.h```, ```gsl_vector.h```, ```gsl_matrix.h``` whereever we use one of them,
 - or have separate C++ headers for each.

And I think in some private feature branch we're already using complex-valued GSL matrices and vectors,
so that's another layer of GSL objects.

**Comment by fredRos** [comment]
Wouldn't it suffice to `#include <gsl_interface.hh>` and it loads the required headers? It would be OK for me. I agree, the implementation for every gsl data type we use is a  bit lengthy but it provides a clean solution at the call site

**Comment by dvandyk** [comment]
@mreboud Would you like to try your hand on this one?

**Comment by mreboud** [comment]
I will be happy to try!
