### ISSUE TITLE
New example notebook showing calculation of simpler theory uncertainty 

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#712]
Suggested to Danny to add a new example notebook showing the calculation of the theory uncertainty for an observable without a kinematic argument, e.g. something like DeltaMs or Bs->mu mu.

For DeltaMs, this would need two parts:
- [ ] Add the appropriate constraints on the meson mixing bag parameters
- [ ] Write an example notebook to add to the other EOS examples

**Comment by dvandyk** [comment]
I would highly suggest to use $\bar{B}_s\to \mu^+\mu^-$ instead of $\Delta m_s$, since it is easier from the point of view of the computing the hadronic uncertainties.

**Comment by dvandyk** [comment]
@MJKirk I have just pushed a branch ``issue712``, adding
 - [x] a commit to export ``B_c->lnu::BR``, which has only a single hadronic matrix element, no kinematics, and is thematically connected to the b->clnu decays that populate all our examples;
 - [ ] a WIP commit that restructures the predictions notebook and add an analysis (predictions.yaml)

**Comment by MJKirk** [comment]
Cheers Danny, the example outline looks good. The $B_s \to \mu \mu$ example I was looking at had an issue where I seemed to be getting much different uncertainties to `flavio`, but I never found time to follow up (one for the dev retreat perhaps?).

**Comment by dvandyk** [comment]
Closing since changes to the notebook have been merged.
