### ISSUE TITLE
Explain parameters used in B->Dlnu theory uncertainty example

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#714]
In the [Estimating Theory Uncertainties](https://eos.github.io/doc/predictions.html#Estimating-Theory-Uncertainties) section of the docs, various B->D::alpha parameters are used, but with minimal explanation.
I propose to add brief text saying that they are parameters in some particular parametrisation of the form factors and maybe a link to the paper where they are defined (made marginally more complicated by the fact that they are called BSZ2015 parameters but this is a pseudoscalar decay and this definition is really from a later paper by Danny, not the BSZ 2015 paper)

**Comment by mreboud** [comment]
Good point.

The name BSZ will certainly be changed into SSE (for Simplified Series Expansion) since we started to use it for almost every parameters ><

**Comment by mreboud** [comment]
Closed by #726
