### ISSUE TITLE
Add warning not to set parameter values directly

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#715]
Add a warning somewhere around here
https://github.com/eos/eos/blob/b639be8d351148c34f632c5877dfd89952a1283c/examples/basics.ipynb#L86

that if you directly modify an eos parameter (e.g. like `m_mu = 1.779` rather than `m_mu.set(1.779)`) nothing immediately breaks, but now `m_mu` is just a number rather than an eos.Parameter

**Comment by MJKirk** [comment]
Something like https://nbsphinx.readthedocs.io/en/0.9.3/markdown-cells.html#Info/Warning-Boxes

**Comment by mreboud** [comment]
Certainly a good idea, let me see if I can do that.

**Comment by mreboud** [comment]
Well, all well thought it is a bit obvious, no?
But if you think it is worth it, I suggest to add

> Caution: If you evaluate ``m_mu = 1.779``, you will just make ``m_mu`` a double instead of an ``eos.Parameter``

Let me know what you think @MJKirk @dvandyk !

**Comment by MJKirk** [comment]
Perhaps it is obvious - I think I was thinking of the masses being properties of a class rather than a class object itself, and therefore you could directly set them using `=`. And I think the way the documentation pulls out `m_mu` as an individual variable encouraged me to play with it directly.

But I think my opinion would be that early on the documentation it doesn't hurt to state the obvious :)

**Comment by mreboud** [comment]
Closed by #726
