### ISSUE TITLE
Potential typo in install instructions

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#718]
Is this part
https://github.com/eos/eos/blob/b639be8d351148c34f632c5877dfd89952a1283c/doc/installation.rst?plain=1#L306-L312
supposed to be commented out, or is this a rogue #?

**Comment by mreboud** [comment]
Thanks for spotting this @MJKirk.
I also think that the two `#` should be removed.

Can you also profit from this modification to tell the user that the `-j` option for make might be problematic on small laptops?
Something like:
``Depending on the accessible RAM of your machine, you might have to reduce the numbers of used core when making. In this case use e.g. `-j4`
``
