### ISSUE TITLE
Observable plotter doesn't allow to plot against parameter values (sort of)

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#725]
The documentation says you can plot an observable as a function of one of its parameters ([see here](https://eos.github.io/doc/api/python.html#plotting-observables)).

But currently the code gives an error if you don't give the variable option
https://github.com/eos/eos/blob/f3c073bf2bb9a2aa2af7740ab4a905a68c2c90b8/python/eos/plot/plotter.py#L492-L493

If you pass a parameter name as the variable it does plot the right thing at least, but either the code or docstring needs changing.

**Comment by dvandyk** [comment]
That's not good. When you fix it, can you please also add a test case to ensure this does not happen again?

**Comment by MJKirk** [comment]
Closed in #737
