### ISSUE TITLE
Interface to EOS datasets via Wilson

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#745]
As discussed with @jacoterh, an interface to SMEFiT for example should
- [x] provide means to iterate over all low-energy EOS-provided likelihoods, which each feature a unique name;
- [x] be able to download new datasets;
- [x] provide metadata on each likelihood: authors, DOI, WET basis, list of WET Wilson coefficients in order, the type of test-statistic (if applicable);
- [x] provide a means to create a callable object that accepts the WET Wilson coefficients as an iterable and returns $-2 \ln L$.

**Comment by dvandyk** [comment]
Resolved by #845.

**Comment by jacoterh** [comment]
Hi @dvandyk , thanks a lot for these additional features! 

I installed the latest version, made it talk to SMEFiT and initialised an EOS DataSet object with `eos_dataset = eos.DataSets()` as discussed. However, when I call its `likelihood` method using `eos_dataset(id="2023-01v2", likelihood="WET-ublnu")` I am getting the following error message:

```
eos_dataset.likelihood(id, likelihood)
*** RuntimeError: Path /user/jthoeve/.cache/eos/2023-01v2/ublnu-wet-LMNRvD2023.yaml does not exist
Traceback (most recent call last):
  File "/project/theorie/jthoeve/miniconda3/envs/smefit_wilson/lib/python3.10/site-packages/eos/datasets.py", line 206, in likelihood
    f = eos.MixtureDensity(os.path.join(self.storage_directory, id, likelihood.filename))
  File "/project/theorie/jthoeve/miniconda3/envs/smefit_wilson/lib/python3.10/site-packages/eos/data/native.py", line 174, in __init__
    raise RuntimeError(f'Path {path} does not exist')

```

It seems this specific dataset cannot be found? Do you or @mreboud reproduce this?

**Comment by mreboud** [comment]
> Hi @dvandyk , thanks a lot for these additional features!
> 
> I installed the latest version, made it talk to SMEFiT and initialised an EOS DataSet object with `eos_dataset = eos.DataSets()` as discussed. However, when I call its `likelihood` method using `eos_dataset(id="2023-01v2", likelihood="WET-ublnu")` I am getting the following error message:
> 
> ```
> eos_dataset.likelihood(id, likelihood)
> *** RuntimeError: Path /user/jthoeve/.cache/eos/2023-01v2/ublnu-wet-LMNRvD2023.yaml does not exist
> Traceback (most recent call last):
>   File "/project/theorie/jthoeve/miniconda3/envs/smefit_wilson/lib/python3.10/site-packages/eos/datasets.py", line 206, in likelihood
>     f = eos.MixtureDensity(os.path.join(self.storage_directory, id, likelihood.filename))
>   File "/project/theorie/jthoeve/miniconda3/envs/smefit_wilson/lib/python3.10/site-packages/eos/data/native.py", line 174, in __init__
>     raise RuntimeError(f'Path {path} does not exist')
> ```
> 
> It seems this specific dataset cannot be found? Do you or @mreboud reproduce this?

I think you have to download it first, with `eos_dataset.download`.
