### ISSUE TITLE
sample_nested task documentation could be improved

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#763]
E.g. for sample_nested it just says 
https://github.com/eos/eos/blob/00b5d008feaf8e52525082bf87028b15bb046060/python/eos/tasks.py#L467
and something similar in the eos-analysis script.
All that is actually put in /nested is just a log file, but then also a DynestyResults object gets exported in /dynesty_results and an ImportanceSamples exported in /samples
https://github.com/eos/eos/blob/00b5d008feaf8e52525082bf87028b15bb046060/python/eos/tasks.py#L491-L493
So this should be explained in some way

There's also some obviously wrong parts in sample_nested and predict_observables which refer to PMC samples rather than ImportanceSamples, which I already fixed in MJKirk/eos@dcdcd9394fe2caaadc435f13ff153d7835b61db4

**Comment by dvandyk** [comment]
From the discussion today:
- Give up ``/dynesty_results``: all files produced directly by ``sample-nested`` should end up in ``/nested``. Keep ``/samples`` for compatibility with / use by downstream tasks.

**Comment by dvandyk** [comment]
Can we close this issue?

**Comment by MJKirk** [comment]
Closed in #767
