### ISSUE TITLE
Various latex issues in observable descriptions

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#768]
The dollar signs are not needed (here and below)
https://github.com/eos/eos/blob/3c96bc42c46c4464128711f77683ea5b4bc94277/eos/scattering/observables.cc#L34
and so they appear wrong in the documentation (see https://eos.github.io/doc/observables.html#observables-in-ee-to-c-bar-c-processes)

**Comment by MJKirk** [comment]
Also 
https://eos.github.io/doc/observables.html#observables-in-lambda-b-to-lambda-nu-bar-nu-decays
and
https://eos.github.io/doc/observables.html#bmmtodcaaslnucocoftildeunl

**Comment by dvandyk** [comment]
Let's systematically prevent (some) of these problems from happening in the future, by checking for (erroneous) use of ``$`` signs in ``eos/observable_TEST.cc``.
