### ISSUE TITLE
Use two sets of parameters to describe b->clnu Wilson Coefficients in the WCScanModel

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#78]
Rename/copy existing parameters from the naming scheme ```b->clnu::Re{cVL}``` to both
```b->cenue::Re{cVL}``` and ```b->cmunumu::Re{cVL}```. Ditto for all the other coefficients (```Im{cVL}, Re{cVR}, ... ```). Also ditto for ```b->ulnu``` transitions.

This requires simultaneous changes to
 - ```eos/parameters/b-to-c-cc.yaml``` (renaming the parameters);
 - ```eos/utils/wilson_scan_model.cc``` around line 283 and 222, see line 147 for inspiration.

**Comment by akokulu7** [comment]
Done, together with Christoph and pushed to github.
