### ISSUE TITLE
Markup wrong 

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#812]
I missed out a newline line here so it renders wrong. Will fix shortly
https://github.com/eos/eos/blob/46cf0d2b30b34b8bdcdf36bae8a50be8631766ea/doc/installation.rst?plain=1#L216-L218

**Comment by dvandyk** [comment]
Can you check with the pre-commit hook [rstcheck/rstcheck](https://github.com/rstcheck/rstcheck)?
