### ISSUE TITLE
HierarchicalClustering produces asymmetric covariance matrices for the output components

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#83]
[CCing @kkvos]

For a B->pipi project we produced very long Markov chains (400k states or longer).
We issued commands to produce a single output component from >200 inputs. We
checked that all input components are symmetric within a tolerance of 1e-7. We find
that the output component is asymmetric, with absolute asymmetries of up to 110,
and relative asymmetries of up to 17%. From a first code review, the [code in question](https://github.com/eos/eos/blob/master/eos/statistics/hierarchical-clustering.cc#L164-L211)
seems to ensure that the results **should be** symmetric. We explicitly tested it by
throwing an InternalError, and find it is not symmetric.

**Comment by dvandyk** [comment]
@fredRos we found two bugs!

The old code is:
```C++
                    // sigma = (mu'_j - mu_i) (mu'_j - mu_i)^T
                    gsl_blas_dsyr(CblasUpper, 1.0, mu_diff, sigma);
```
1. This accumulates the previous results in ```sigma```.
2. ```dsyr``` is the operation to produce a symmetric BLAS matrix in upper/lower triangular shape.
Since this is added to existing **dense** matrices, the triangular shape can cause severe asymmetries
when reducing a larger number of input components to a small number if outputs. Impressive that
this worked in the first place. 

The proposed solution is this:
```C++
                    // sigma = (mu'_j - mu_i) (mu'_j - mu_i)^T
                    gsl_matrix_set_all(sigma, 0);
                    gsl_blas_dger(1.0, mu_diff, mu_diff, sigma);
```

FYI: after fixing it this way, the PMC converges after one step with a perplexity in excess of 90%.

**Comment by fredRos** [comment]
I'm glad you found a solution already. I don't understand why this should only happen when reducing from many to few components. In my opinion, that's always the case so I wonder how we missed this bug before? Perhaps things should have converged much faster...
