### ISSUE TITLE
Add option to rasterize artists in plotting routines

### ISSUE THREAD

**Issue by pluegh** [eos/eos#851]
For applications that render many vector objects, e.g., scatter plots with a large number of points, it is useful to rasterize the respective artists. This keeps the remnant objects such as the axis and other artists of the plot as vectors.

Some notes:
 - Routines such as corner plot should create the rasterized artists with the kwarg `rasterized` (see [here](https://matplotlib.org/stable/api/artist_api.html)).
 - The plotting routine must specify the dpi of the bitmap and hardcode the artists that should be rasterized. I suggest two optional arguments `rasterized=False` and `dpi=300` to keep things simple for the user. 
 - Setting the figure dpi should be done at figure creation.

**Comment by dvandyk** [comment]
As discussed during today's dev meeting, @mreboud will try to switch to a different backend (e.g. ``PDF`` rather than ``PGF``) to see if the issues are solved by that.

**Comment by mreboud** [comment]
Closed by #936, plots are now rasterized by default.
