### ISSUE TITLE
Clarify the use of `UnspecifiedOptionError` and `UnknownOptionError` throughout EOS

### ISSUE THREAD

**Issue by mreboud** [eos/eos#853]
It is specifically unclear here: https://github.com/eos/eos/blob/40107eda4a3fe1dce52484a73ac55e4b7a64ca9d/eos/form-factors/form-factor-adapter.hh#L75
and will be unclear in the future `NonleptonicAmplitudesAdapter`

**Comment by dvandyk** [comment]
To me, it seems like this is already pretty clear:
```C++
    /*!
     * UnknownOptionError is thrown when an Options object does not contain a value for a given option key.
     */
    struct UnknownOptionError :
        public Exception
    {
        UnknownOptionError(const std::string & key) throw ();
    };
    
    // ...
    
    /*!
     * UnspecifiedOptionError is thrown by an observable provider or similar when a mandatory option is not specified.
     */
    struct UnspecifiedOptionError :
        public Exception
    {
        UnspecifiedOptionError(const std::string & key, const std::string & allowed = "") throw ();
    };
```

I have pushed a feature branch to ``issue853`` that converts ``FormFactorAdapter`` to use a ``SpecifiedOption``. I suggest to copy the code from that for the B->PP branch.
