### ISSUE TITLE
Parallelize `nested_sampling`?

### ISSUE THREAD

**Issue by lorenzennio** [eos/eos#922]
Have you ever tried to parallelize `nested_sampling`? According to the `dynesty` docs this is possible with the [Schwimmbad](https://schwimmbad.readthedocs.io/en/latest/index.html) package:

https://dynesty.readthedocs.io/en/stable/faq.html

(look for "I would like to run `dynesty` across multiple nodes on a cluster. How do I do that ?")

Should also be easy to implement, by simply allowing for kwargs in `nested_sampling` and passing them through to `dynesty.DynamicNestedSampler`. Apparently, this is as easy as passing the `pool` argument.

**Comment by mreboud** [comment]
This is not necessarily needed. What usually takes time in the sampling is the evaluation of the observables,  and this evaluation is already parallelized, but I would be curious to know what it gives!

**Comment by dvandyk** [comment]
I concur with @mreboud here. @lorenzennio I hope you don't mind me closing this as ``wontfix``.
