### ISSUE TITLE
find-mode default behaviour

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#931]
Currently `find-mode` defaults to starting from a random point if no option is passed on the command line.
I think it would be better to either default to using samples, or not default to anything and require an option to be specified.

**Comment by mreboud** [comment]
I think that the current behaviour is the one we want. For many small fits, starting from a random point proves efficient. Removing this default option would make EOS harder to use, I think.

**Comment by dvandyk** [comment]
I kind of liked the idea to make one of the three existing modes of operation (init randomly, from importance samples, from chains) a mandatory argument. But I see where @mreboud is coming from: it's nice to have something that kind of works as a default.

**Comment by mreboud** [comment]
On the other hand, as discussed in the EOS dev meeting, it would make sense to:

1. Complete the documentation
2. Raise an error instead of a warning if the optimization failed, and maybe add a message if "random" was used

**Comment by MJKirk** [comment]
Closed in #951
